CREATE SEQUENCE IF NOT EXISTS categories_itemseq_seq
    START WITH 10 INCREMENT BY 10;

CREATE SEQUENCE IF NOT EXISTS subCategories_itemseq_seq
    START WITH 10 INCREMENT BY 10;

CREATE SEQUENCE IF NOT EXISTS questions_itemseq_seq
    START WITH 10 INCREMENT BY 10;
