import type { Metadata } from "next";
import { Google_Sans } from "next/font/google";
import "./globals.css";

const googleSans = Google_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin", "thai"],
});


export const metadata: Metadata = {
  title: "Respondents",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${googleSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
