FROM node:24-alpine AS build

WORKDIR /app

COPY web/package*.json ./

RUN npm install

COPY web/ .

RUN npm run build

FROM node:24-alpine AS production

WORKDIR /app

COPY --from=build /app/package.json .
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/next.config.ts ./next.config.ts

EXPOSE 3000

CMD ["npx", "next", "start"]